Jsonp
CodedPoetry/CodedPoetry.github.io pull request #9
Opened 2017-08-31 11:09 UTC by a2ron

2017-08-31 11:33 UTC, fllaca commented
Gracias tio!! Otro de tus artículos sorpresa! :D Te he puesto una cosa pequeña que hay que cambiar, pero nada más. Eres un crack!

2017-08-31 11:35 UTC, fllaca requested changes

2017-08-31 11:35 UTC, fllaca commented on _posts/2017-08-31-jsonp.md
> +twitter_text: JSONP: what and how
Please, pon "JSONP: what and how" entre comillas, el analizador de texto se raya al ver otros dos puntos en la linea.

2017-09-01 12:53 UTC, a2ron commented
done!

2017-09-01 13:17 UTC, fllaca approved these changes

2017-09-01 13:17 UTC, merged